# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gbvm < Formula
  desc "Version manager for go, currently golangci-lint and mockery"
  homepage ""
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Abdulsametileri/go-binary-version-manager/releases/download/v0.0.2/go-binary-version-manager_0.0.2_Darwin_arm64.tar.gz"
      sha256 "382cdf72ef3ab7ab3730fc48a714dc2d0d68f62f10fd88b5c60f310eebf915cd"

      def install
        bin.install "gbvm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Abdulsametileri/go-binary-version-manager/releases/download/v0.0.2/go-binary-version-manager_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "e00b3627732cf73ca81f126110454a5c24b80effb5765a5c66f60f8fb783e125"

      def install
        bin.install "gbvm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Abdulsametileri/go-binary-version-manager/releases/download/v0.0.2/go-binary-version-manager_0.0.2_Linux_arm64.tar.gz"
      sha256 "6c201b6d4b822ea3c155dea375295bb05c9cf135aeee76df408a90f58c229618"

      def install
        bin.install "gbvm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Abdulsametileri/go-binary-version-manager/releases/download/v0.0.2/go-binary-version-manager_0.0.2_Linux_x86_64.tar.gz"
      sha256 "f4fd0e6347eefa0baae06c8936d454978e1b675e36b627120a8c2edaaffecc81"

      def install
        bin.install "gbvm"
      end
    end
  end
end
