# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gbvm < Formula
  desc "Version manager for go, currently golangci-lint and mockery"
  homepage ""
  version "0.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Abdulsametileri/go-binary-version-manager/releases/download/v0.0.4/go-binary-version-manager_0.0.4_Darwin_arm64.tar.gz"
      sha256 "56d3dcd5e33ce8f7b3fc4cac3d80fb2b442f0284efd40b8ad1d1eb8fbdcf98c5"

      def install
        bin.install "gbvm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Abdulsametileri/go-binary-version-manager/releases/download/v0.0.4/go-binary-version-manager_0.0.4_Darwin_x86_64.tar.gz"
      sha256 "6cf1c8357aa14396d9f2c9e234f3eb2d074b659939a30a6f0b7c3ea36421a352"

      def install
        bin.install "gbvm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Abdulsametileri/go-binary-version-manager/releases/download/v0.0.4/go-binary-version-manager_0.0.4_Linux_arm64.tar.gz"
      sha256 "296d5e8781fa426aa1b51bd6a6e5f3ddedb1cc5691459e65d96c721a562b17ab"

      def install
        bin.install "gbvm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Abdulsametileri/go-binary-version-manager/releases/download/v0.0.4/go-binary-version-manager_0.0.4_Linux_x86_64.tar.gz"
      sha256 "f2425109fbdbc353feb0af756d491460a3127877a6f1c3001688c52481771959"

      def install
        bin.install "gbvm"
      end
    end
  end
end
