# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vx < Formula
  desc "vX is a basic version control system"
  homepage ""
  version "1.0.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Abdulsametileri/vX/releases/download/v1.0.6/vX_1.0.6_Darwin_arm64.tar.gz"
      sha256 "7294bf2de5fdbfa5469b2eb801a738a7c6ebbce12ef0d037d6746cbff2ea9a34"

      def install
        bin.install "vx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Abdulsametileri/vX/releases/download/v1.0.6/vX_1.0.6_Darwin_x86_64.tar.gz"
      sha256 "591ede81bf0d9fdac10e8575051e3d91b5f7cb8a1ea9a99dc724001de675d237"

      def install
        bin.install "vx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Abdulsametileri/vX/releases/download/v1.0.6/vX_1.0.6_Linux_arm64.tar.gz"
      sha256 "9cf167724ebe5417bc69b52ee92d4bfcf8dec272a69c80075d3dc3abb1173140"

      def install
        bin.install "vx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Abdulsametileri/vX/releases/download/v1.0.6/vX_1.0.6_Linux_x86_64.tar.gz"
      sha256 "252e705f9815e683619fd6fa49c6e68f9150aa518ad4631171c474723d688e1d"

      def install
        bin.install "vx"
      end
    end
  end
end
