# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VX < Formula
  desc "vX is a basic version control system"
  homepage ""
  version "1.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Abdulsametileri/vX/releases/download/v1.0.2/vX_1.0.2_Darwin_arm64.tar.gz"
      sha256 "e8d2f62ff84097fdd92f9ecb0e5dbf4dee9c998b96574453aceae7071c6d5690"

      def install
        bin.install "vx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Abdulsametileri/vX/releases/download/v1.0.2/vX_1.0.2_Darwin_x86_64.tar.gz"
      sha256 "0733c4592b0717e3b17417571e1183113e8e6cd3b5bf4718a2beb29972057ed5"

      def install
        bin.install "vx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Abdulsametileri/vX/releases/download/v1.0.2/vX_1.0.2_Linux_arm64.tar.gz"
      sha256 "d92cb3d7b8c1f4126c3dc220c785623e9a136e1fbd32138f19a8dfa7c3b74b2a"

      def install
        bin.install "vx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Abdulsametileri/vX/releases/download/v1.0.2/vX_1.0.2_Linux_x86_64.tar.gz"
      sha256 "966cbde8e452428edcaa53a23c6b31287363c736481353888a89497bbbc1499b"

      def install
        bin.install "vx"
      end
    end
  end
end
