# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vx < Formula
  desc "vX is a basic version control system"
  homepage ""
  version "1.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Abdulsametileri/vX/releases/download/v1.0.3/vX_1.0.3_Darwin_arm64.tar.gz"
      sha256 "96a5d2e0497e5767607369a3294070653e6c6751f35f6ae3a4c41c59c067a5a8"

      def install
        bin.install "vx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Abdulsametileri/vX/releases/download/v1.0.3/vX_1.0.3_Darwin_x86_64.tar.gz"
      sha256 "fa47bcc68a42005ee84d3e5961de29d4e9b915c0658eb368b25f17c2f4c30956"

      def install
        bin.install "vx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Abdulsametileri/vX/releases/download/v1.0.3/vX_1.0.3_Linux_arm64.tar.gz"
      sha256 "a75c64df7e730a0adf64a4acfdab093f5abe4ce5104d0a2949add0ab80c73380"

      def install
        bin.install "vx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Abdulsametileri/vX/releases/download/v1.0.3/vX_1.0.3_Linux_x86_64.tar.gz"
      sha256 "b143db20b732f8888592755ec3e1ab56ee06d7d5ea81ad6800986e5c652a8d87"

      def install
        bin.install "vx"
      end
    end
  end
end
